final_space = true
version = 3

[var]
prompt = "|>"

[palette]
fg = "#ff00aa"
bg = "transparent"

[[blocks]]
    type = "prompt"
    alignment = "left"

  [[blocks.segments]]
  type = "path"
  style = "plain"
  template = "{{ .Path }}"
  foreground = "p:fg"
  background = "p:bg"

[[blocks]]
  type = "rprompt"
  alignment = "right"

  [[blocks.segments]]
      type = "executiontime"
      style = "plain"
      template = "{{ .FormattedMs }}"
      foreground = "p:fg"
      background = "p:bg"
          [blocks.segments.properties]
          threshold = 0
          style = "amarillo"

[[blocks]]
  type = "prompt"
  alignment = "left"
  newline = true

  [[blocks.segments]]
    type="text"
    style = "plain"
    template = "{{ .Var.prompt }}"
    foreground = "p:fg"
    background = "p:bg"

[transient_prompt]
template = "{{ .Var.prompt }} "
foreground = "p:fg"
background = "p:bg"
